// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type FantasyDraft struct {
	ID         int64          `json:"id"`
	LeagueID   int64          `json:"league_id"`
	TeamID     int64          `json:"team_id"`
	PlayerID   int64          `json:"player_id"`
	Round      int64          `json:"round"`
	PickNumber int64          `json:"pick_number"`
	DraftTime  sql.NullString `json:"draft_time"`
}

type FantasyLeague struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	SeasonID   int64          `json:"season_id"`
	TeamsCount int64          `json:"teams_count"`
	QbCount    sql.NullInt64  `json:"qb_count"`
	RbCount    sql.NullInt64  `json:"rb_count"`
	WrCount    sql.NullInt64  `json:"wr_count"`
	TeCount    sql.NullInt64  `json:"te_count"`
	FlexCount  sql.NullInt64  `json:"flex_count"`
	KCount     sql.NullInt64  `json:"k_count"`
	DstCount   sql.NullInt64  `json:"dst_count"`
	BenchCount sql.NullInt64  `json:"bench_count"`
	Ppr        sql.NullInt64  `json:"ppr"`
	CreatedAt  sql.NullString `json:"created_at"`
}

type FantasyMatchup struct {
	ID             int64           `json:"id"`
	LeagueID       int64           `json:"league_id"`
	Week           int64           `json:"week"`
	HomeTeamID     int64           `json:"home_team_id"`
	AwayTeamID     int64           `json:"away_team_id"`
	HomeScore      sql.NullFloat64 `json:"home_score"`
	AwayScore      sql.NullFloat64 `json:"away_score"`
	IsPlayoff      sql.NullInt64   `json:"is_playoff"`
	IsChampionship sql.NullInt64   `json:"is_championship"`
	Completed      sql.NullInt64   `json:"completed"`
}

type FantasyPlayerScore struct {
	ID       int64           `json:"id"`
	LeagueID int64           `json:"league_id"`
	TeamID   sql.NullInt64   `json:"team_id"`
	PlayerID int64           `json:"player_id"`
	Week     int64           `json:"week"`
	SeasonID int64           `json:"season_id"`
	Points   sql.NullFloat64 `json:"points"`
}

type FantasyRoster struct {
	ID        int64         `json:"id"`
	TeamID    int64         `json:"team_id"`
	PlayerID  int64         `json:"player_id"`
	Position  string        `json:"position"`
	IsStarter sql.NullInt64 `json:"is_starter"`
}

type FantasyScoringRule struct {
	ID                        int64           `json:"id"`
	LeagueID                  int64           `json:"league_id"`
	PassingYardsPerPoint      sql.NullFloat64 `json:"passing_yards_per_point"`
	PassingTouchdownPoints    sql.NullFloat64 `json:"passing_touchdown_points"`
	PassingInterceptionPoints sql.NullFloat64 `json:"passing_interception_points"`
	RushingYardsPerPoint      sql.NullFloat64 `json:"rushing_yards_per_point"`
	RushingTouchdownPoints    sql.NullFloat64 `json:"rushing_touchdown_points"`
	ReceivingYardsPerPoint    sql.NullFloat64 `json:"receiving_yards_per_point"`
	ReceivingTouchdownPoints  sql.NullFloat64 `json:"receiving_touchdown_points"`
	ReceptionPoints           sql.NullFloat64 `json:"reception_points"`
	FieldGoal039Points        sql.NullFloat64 `json:"field_goal_0_39_points"`
	FieldGoal4049Points       sql.NullFloat64 `json:"field_goal_40_49_points"`
	FieldGoal50PlusPoints     sql.NullFloat64 `json:"field_goal_50_plus_points"`
	ExtraPointPoints          sql.NullFloat64 `json:"extra_point_points"`
	SackPoints                sql.NullFloat64 `json:"sack_points"`
	InterceptionPoints        sql.NullFloat64 `json:"interception_points"`
	FumbleRecoveryPoints      sql.NullFloat64 `json:"fumble_recovery_points"`
	DefensiveTouchdownPoints  sql.NullFloat64 `json:"defensive_touchdown_points"`
	SafetyPoints              sql.NullFloat64 `json:"safety_points"`
	TwoPointConversionPoints  sql.NullFloat64 `json:"two_point_conversion_points"`
	FumbleLostPoints          sql.NullFloat64 `json:"fumble_lost_points"`
}

type FantasyTeam struct {
	ID            int64           `json:"id"`
	LeagueID      int64           `json:"league_id"`
	Name          string          `json:"name"`
	OwnerName     string          `json:"owner_name"`
	IsUser        sql.NullInt64   `json:"is_user"`
	DraftPosition sql.NullInt64   `json:"draft_position"`
	Wins          sql.NullInt64   `json:"wins"`
	Losses        sql.NullInt64   `json:"losses"`
	TieGames      sql.NullInt64   `json:"tie_games"`
	PointsFor     sql.NullFloat64 `json:"points_for"`
	PointsAgainst sql.NullFloat64 `json:"points_against"`
}

type NflGame struct {
	ID         int64          `json:"id"`
	SeasonID   int64          `json:"season_id"`
	Week       int64          `json:"week"`
	HomeTeamID int64          `json:"home_team_id"`
	AwayTeamID int64          `json:"away_team_id"`
	HomeScore  sql.NullInt64  `json:"home_score"`
	AwayScore  sql.NullInt64  `json:"away_score"`
	GameDate   string         `json:"game_date"`
	GameTime   string         `json:"game_time"`
	Status     sql.NullString `json:"status"`
}

type NflPlayer struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Position     string         `json:"position"`
	TeamID       sql.NullInt64  `json:"team_id"`
	JerseyNumber sql.NullInt64  `json:"jersey_number"`
	Status       sql.NullString `json:"status"`
}

type NflTeam struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	City         string `json:"city"`
	Abbreviation string `json:"abbreviation"`
	Conference   string `json:"conference"`
	Division     string `json:"division"`
}

type PlayerStat struct {
	ID                   int64           `json:"id"`
	PlayerID             int64           `json:"player_id"`
	GameID               int64           `json:"game_id"`
	SeasonID             int64           `json:"season_id"`
	Week                 int64           `json:"week"`
	PassingAttempts      sql.NullInt64   `json:"passing_attempts"`
	PassingCompletions   sql.NullInt64   `json:"passing_completions"`
	PassingYards         sql.NullInt64   `json:"passing_yards"`
	PassingTouchdowns    sql.NullInt64   `json:"passing_touchdowns"`
	PassingInterceptions sql.NullInt64   `json:"passing_interceptions"`
	RushingAttempts      sql.NullInt64   `json:"rushing_attempts"`
	RushingYards         sql.NullInt64   `json:"rushing_yards"`
	RushingTouchdowns    sql.NullInt64   `json:"rushing_touchdowns"`
	Targets              sql.NullInt64   `json:"targets"`
	Receptions           sql.NullInt64   `json:"receptions"`
	ReceivingYards       sql.NullInt64   `json:"receiving_yards"`
	ReceivingTouchdowns  sql.NullInt64   `json:"receiving_touchdowns"`
	FieldGoalsMade       sql.NullInt64   `json:"field_goals_made"`
	FieldGoalsAttempted  sql.NullInt64   `json:"field_goals_attempted"`
	ExtraPointsMade      sql.NullInt64   `json:"extra_points_made"`
	ExtraPointsAttempted sql.NullInt64   `json:"extra_points_attempted"`
	Sacks                sql.NullFloat64 `json:"sacks"`
	Interceptions        sql.NullInt64   `json:"interceptions"`
	FumbleRecoveries     sql.NullInt64   `json:"fumble_recoveries"`
	DefensiveTouchdowns  sql.NullInt64   `json:"defensive_touchdowns"`
	Safeties             sql.NullInt64   `json:"safeties"`
	FumblesLost          sql.NullInt64   `json:"fumbles_lost"`
	TwoPointConversions  sql.NullInt64   `json:"two_point_conversions"`
}

type Season struct {
	ID        int64         `json:"id"`
	Year      int64         `json:"year"`
	StartDate string        `json:"start_date"`
	EndDate   string        `json:"end_date"`
	Current   sql.NullInt64 `json:"current"`
}
