// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateGame(ctx context.Context, arg CreateGameParams) error
	DeleteGame(ctx context.Context, eventID int64) error
	GetAllGames(ctx context.Context) ([]*NflGame, error)
	GetAllGamesBySeasonAndWeek(ctx context.Context, arg GetAllGamesBySeasonAndWeekParams) ([]*NflGame, error)
	GetGame(ctx context.Context, eventID int64) (*NflGame, error)
	UpdateGame(ctx context.Context, arg UpdateGameParams) error
}

var _ Querier = (*Queries)(nil)
